<a href="https://colab.research.google.com/github/Jay-D21/Deep-Learning/blob/main/Introduction%20to%20Matrix%20Operations%20using%20Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing Important Library/Package

In [ ]:
import tensorflow as tf

#Task 2: Basic Operation


In [ ]:
tensor_a = tf.constant([[7,9],[5,3]], dtype = tf.float32)
tensor_b = tf.constant([[2,6],[8,4]], dtype = tf.float32)

#Addition
addition_result = tf.add(tensor_a, tensor_b)

print(addition_result.numpy())

[[ 9. 15.]
 [13.  7.]]


In [ ]:
#subtraction
subtraction_result = tf.subtract(tensor_a, tensor_b)

print(subtraction_result.numpy(), "C233")

[[ 5.  3.]
 [-3. -1.]] C233


In [ ]:
#Multiplication
multiplication_result = tf.multiply(tensor_a, tensor_b)

print(multiplication_result.numpy())

[[14. 54.]
 [40. 12.]]


In [ ]:
#Devision
division_result = tf.divide(tensor_a, tensor_b)

print(division_result.numpy())

[[3.5   1.5  ]
 [0.625 0.75 ]]


In [ ]:
from functools import reduce
reduce_mean_a = tf.reduce_mean(tensor_a)
reduce_mean_b = tf.reduce_mean(tensor_b)


print(reduce_mean_a.numpy(),"\n",reduce_mean_b.numpy())

6.0 
 5.0


In [ ]:
reduce_sum_a = tf.reduce_sum(tensor_a)
reduce_sum_b = tf.reduce_sum(tensor_b)

print(reduce_sum_a.numpy(),"\n",reduce_sum_b.numpy())

24.0 
 20.0


In [ ]:
reduce_sum0 = tf.reduce_sum(tensor_a, axis = 0)
reduce_sum1 = tf.reduce_sum(tensor_b, axis = 1)

print(reduce_sum0.numpy())
print(reduce_sum1.numpy())

[12. 12.]
[ 8. 12.]


#Task 3: Performing Linear Algebra Operations

In [ ]:
import tensorflow as tf

In [ ]:
#Matrix Multiplication
matrix_multiplication_result = tf.matmul(tensor_a, tensor_b)

print("Matrix Multiplication Result:")
print(matrix_multiplication_result.numpy())

Matrix Multiplication Result:
[[86. 78.]
 [34. 42.]]


In [ ]:
#Transpose
transpose_a = tf.transpose(tensor_a)
transpose_b = tf.transpose(tensor_b)

print("Transpose of tensor_a:")
print(transpose_a.numpy())

print("Transpose of tensor_b:")
print(transpose_b.numpy())

Transpose of tensor_a:
[[7. 5.]
 [9. 3.]]
Transpose of tensor_b:
[[2. 8.]
 [6. 4.]]


In [ ]:
#Determinant (for square Matrix)
determinant = tf.linalg.det(tensor_a)

print("Determinant of tensor_a:")
print(determinant.numpy())

Determinant of tensor_a:
-24.0


In [ ]:
#Inverse (for invertable matrix)
try:
  inverse = tf.linalg.inv(tensor_a)
  print("Inverse of tensor_a:")
  print(inverse.numpy())
except tf.errors.InvalidArgumentError as e:
  print("Error: Matrix is not invertable.")

Inverse of tensor_a:
[[-0.125       0.37500003]
 [ 0.20833333 -0.29166666]]


#Task 4: Derivative and Higher Order Derivative Using Gradient Tape

In [ ]:
x = tf.Variable(3.0)

with tf.GradientTape(persistent = True) as tape:
  #Defining function f(x) = x^3
  f = x**3
  #compute the first derivative
  df_dx = tape.gradient(f, x)
  #compute the second derivative
  d2f_dx2 = tape.gradient(df_dx, x)


print(f"\nf(x) at x = {x.numpy()}: {f.numpy()}")
print(f"First derivative (df/dx) at x = {x.numpy()}: {df_dx.numpy()}")
print(f"Second derivative (d2f/dx2) at x = {x.numpy()}: {d2f_dx2.numpy()}")


f(x) at x = 3.0: 27.0
First derivative (df/dx) at x = 3.0: 27.0
Second derivative (d2f/dx2) at x = 3.0: 18.0


#Task 5: Compute WX+b using Tensorflow where W, X, and b are drawn from a random normal distribution. W is of shape (4, 3), X is (3,1) and b is (4,1)  

In [ ]:
# Compute WX+b using TensorFlow with randomly initialized tensors
tf.random.set_seed(42)
W = tf.random.normal(shape = (4, 3))
X = tf.random.normal(shape = (3, 1))
b = tf.random.normal(shape = (4, 1))

result = tf.matmul(W, X) + b

print("W:\n", W.numpy())
print("\nX:\n", X.numpy())
print("\nb:\n", b.numpy())
print("\nResult:\n", result.numpy())

W:
 [[ 0.3274685  -0.8426258   0.3194337 ]
 [-1.4075519  -2.3880599  -1.0392479 ]
 [-0.5573232   0.539707    1.6994323 ]
 [ 0.28893656 -1.5066116  -0.26454744]]

X:
 [[ 0.08422458]
 [-0.86090374]
 [ 0.37812304]]

b:
 [[-0.55909735]
 [-0.5347214 ]
 [ 2.3730333 ]
 [-1.5725931 ]]

Result:
 [[ 0.3146885]
 [ 1.0096543]
 [ 2.5040517]
 [-0.3512416]]


#Task 6: Compute Gradient of sigmoid function using Tensor flow

In [ ]:
# Compute the gradient of the sigmoid function
x = tf.Variable(0.0)

with tf.GradientTape() as tape:
  sigmoid_x = tf.sigmoid(x)

gradient_of_sigmoid = tape.gradient(sigmoid_x, x)

print(f"The gradient of the sigmoid function at x = {x.numpy()} is: {gradient_of_sigmoid.numpy()}")

The gradient of the sigmoid function at x = 0.0 is: 0.25


In [ ]:
x = tf.Variable(0.0)

with tf.GradientTape() as tape:
  sigmoid_x = 1 / (1 + tf.exp(-x))

gradient_of_sigmoid = tape.gradient(sigmoid_x, x)

print(f"The gradient of the sigmoid function at x = {x.numpy()} is: {gradient_of_sigmoid.numpy()}")

The gradient of the sigmoid function at x = 0.0 is: 0.25
